version: '3.0'

networks:
  bridgeN:
    external: true

services:

  fastapi:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/code

    networks:
      - bridgeN

    restart: on-failure